### ISSUE TITLE
SQL Injection found!!!!

### ISSUE THREAD

**Issue by Anjan62** [MontbitTech/WebApp-e-EdPort-LMS#566]
I noticed that while clicking on the delete button in the Action column. It is redirecting us to the main server page. Kindly check. PFA the screenshot for the same.

![image](https://user-images.githubusercontent.com/65858265/101900662-d86c9680-3bd5-11eb-8a69-ac450d256f1b.png)

**Comment by vickyjodha** [comment]
fixed

**Comment by Anjan62** [comment]
Still showing the same.
![image](https://user-images.githubusercontent.com/65858265/102094586-841d1d00-3e48-11eb-8309-61677c16766d.png)

**Comment by krtrthbilory** [comment]
these both are diff. issues as these are diff. apis

**Comment by Anjan62** [comment]
But the issue is still there that is important.

**Comment by krtrthbilory** [comment]
managing issues is more important for someone to understand it. else developer would be trying to fix something else but the issue is diff

**Comment by Anshumanshrivastava** [comment]
fixed
