### ISSUE TITLE
Upload Button not working

### ISSUE THREAD

**Issue by Anjan62** [MontbitTech/WebApp-e-EdPort-LMS#568]
I noticed that while adding the questions in the question tab while clicking on the upload button it is again redirecting us to the main server. Kindly check!

![image](https://user-images.githubusercontent.com/65858265/101901307-dd7e1580-3bd6-11eb-897c-c5a5e17712c2.png)

**Comment by vickyjodha** [comment]
fixed

**Comment by Anjan62** [comment]
It is still showing something went the wrong message. Screenshot sent. Kindly check

**Comment by krtrthbilory** [comment]
where is ss ?

**Comment by Anjan62** [comment]
Check slack.

**Comment by krtrthbilory** [comment]
fixed
